### ISSUE TITLE
2.0

### ISSUE THREAD

**Issue by AwesomeWithRex** [XaleTheCat/fnf-grafex#11]
### Describe your problem here.

There is a mod [I forget what called] and it uses 0.2... What!? Where is that!?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by PurpleSSSnake** [comment]
Oh, i forgot to add "Proto" in engine data

**Comment by PurpleSSSnake** [comment]
We are release soon

**Comment by AwesomeWithRex** [comment]
Ok
