### ISSUE TITLE
Funkin.lua

### ISSUE THREAD

**Issue by Tsakuu** [XaleTheCat/fnf-grafex#16]
### Describe your bug here.

in sources and funkin lua when i compile it say 

E:\JEUX\fnf-grafex-raw>lime test windows
source/FunkinLua.hx:2613: characters 7-36 : Bool should be Int
source/FunkinLua.hx:367: lines 367-371 : Int should be Bool
source/FunkinLua.hx:367: lines 367-371 : ... For function argument 'f'
source/FunkinLua.hx:473: lines 473-476 : Int should be Bool
source/FunkinLua.hx:473: lines 473-476 : ... For function argument 'f'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by justxale** [comment]
You need to update lua jit, look for info in psych repository

**Comment by Tsakuu** [comment]
thanks its working but the arrow are like this and invisibl
![Capture d’écran 2022-07-19 235853](https://user-images.githubusercontent.com/104218299/179855738-d3c85994-1eff-45a0-b458-b14c661141d2.png)
e

**Comment by justxale** [comment]
Is this only on week7?

**Comment by Tsakuu** [comment]
no all week i'll send you the bin ? and maybe all the files ?
![Capture d’écran 2022-07-20 000126](https://user-images.githubusercontent.com/104218299/179856130-7ac61fee-4584-4326-b7ec-8d35c7483d86.png)
?

**Comment by justxale** [comment]
Let's try this

**Comment by Tsakuu** [comment]
okay i just compress and i'll send you

**Comment by Tsakuu** [comment]
[https://mega.nz/file/hScSwDYK#mMVjgSH0e-X_zvv5vBuL7og7kcZKTTWmN5frEflmqJg](url)

**Comment by justxale** [comment]
Got it, ill take a look later

**Comment by Tsakuu** [comment]
okay thanks and too i love your engine but you should make it a reset button to the option menu

bcs maybe its a bug for me idk

**Comment by justxale** [comment]
So, yeah, its prb a bug of options thing
Stay for updates, reset button will be added

**Comment by Tsakuu** [comment]
okay thanks !

**Comment by PurSnake** [comment]
All that added  and fixed.

**Comment by Tsakuu** [comment]
THANKS ITS WORKING i love your engine its very cool

**Comment by Tsakuu** [comment]
you even sorted it's much better
