### ISSUE TITLE
Crash on Stress 

### ISSUE THREAD

**Issue by Pyr0Guy** [XaleTheCat/fnf-grafex#17]
### Describe your bug here.

All my pain in one image
![Grafex_bWu4R95LTP](https://user-images.githubusercontent.com/87705495/181278641-16ef3f9f-df78-40aa-95ec-86e8632883ec.png)

That's all 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i don't edit any of the files

**Comment by justxale** [comment]
Oh god
Haven't i fixed this??

So, my bad, will be repaired in some hours

**Comment by justxale** [comment]
Is this only on Stress song?

**Comment by Pyr0Guy** [comment]
Well yes it's only on Stress

**Comment by justxale** [comment]
Interesting... i haven't found anything wrong, but gonna test todat (yesterday was a really stressful day)

**Comment by justxale** [comment]
Prb fixed

**Comment by justxale** [comment]
Yeah, fixed, just tried out

**Comment by Pyr0Guy** [comment]
> Yeah, fixed, just tried out

Nice, great job
