### ISSUE TITLE
Bug in songs

### ISSUE THREAD

**Issue by min89xd** [XaleTheCat/fnf-grafex#18]
### Describe your bug here.

in songs like zanta the notes appear behind the edges
![image](https://user-images.githubusercontent.com/90361729/183227624-7793f5ed-cf01-4205-a939-4409eff41a46.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by justxale** [comment]
Yeah, saw this thing earlier
Gonna fix

**Comment by min89xd** [comment]
ok i 'm gonna close the issue thanks
